# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "venv",
]

# line length for linting
line-length = 120
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
# select = ["E4", "E7", "E9", "F", ]
select = ["E", "F", "W", "I"]
ignore = []
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
## Allow fix for all enabled rules (when `--fix`) is provided.
#fixable = ["ALL"]
#unfixable = []

[format]
# use double quotes for strings.
quote-style = "double"
# indent with spaces, rather than tabs.
indent-style = "space"
# respect magic trailing commas.
skip-magic-trailing-comma = false
# automatically detect the appropriate line ending.
line-ending = "auto"