name: ruff-check

on:
  push:
    branches:
      - django

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v1
        with:
          args: check .
